# Classification Exercise

We'll be working with some California Census Data, we'll be trying to use various features of an individual to predict what class of income they belogn in (>50k or <=50k). 

Here is some information about the data:

<table>
<thead>
<tr>
<th>Column Name</th>
<th>Type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>age</td>
<td>Continuous</td>
<td>The age of the individual</td>
</tr>
<tr>
<td>workclass</td>
<td>Categorical</td>
<td>The type of employer the  individual has (government,  military, private, etc.).</td>
</tr>
<tr>
<td>fnlwgt</td>
<td>Continuous</td>
<td>The number of people the census  takers believe that observation  represents (sample weight). This  variable will not be used.</td>
</tr>
<tr>
<td>education</td>
<td>Categorical</td>
<td>The highest level of education  achieved for that individual.</td>
</tr>
<tr>
<td>education_num</td>
<td>Continuous</td>
<td>The highest level of education in  numerical form.</td>
</tr>
<tr>
<td>marital_status</td>
<td>Categorical</td>
<td>Marital status of the individual.</td>
</tr>
<tr>
<td>occupation</td>
<td>Categorical</td>
<td>The occupation of the individual.</td>
</tr>
<tr>
<td>relationship</td>
<td>Categorical</td>
<td>Wife, Own-child, Husband,  Not-in-family, Other-relative,  Unmarried.</td>
</tr>
<tr>
<td>race</td>
<td>Categorical</td>
<td>White, Asian-Pac-Islander,  Amer-Indian-Eskimo, Other, Black.</td>
</tr>
<tr>
<td>gender</td>
<td>Categorical</td>
<td>Female, Male.</td>
</tr>
<tr>
<td>capital_gain</td>
<td>Continuous</td>
<td>Capital gains recorded.</td>
</tr>
<tr>
<td>capital_loss</td>
<td>Continuous</td>
<td>Capital Losses recorded.</td>
</tr>
<tr>
<td>hours_per_week</td>
<td>Continuous</td>
<td>Hours worked per week.</td>
</tr>
<tr>
<td>native_country</td>
<td>Categorical</td>
<td>Country of origin of the  individual.</td>
</tr>
<tr>
<td>income</td>
<td>Categorical</td>
<td>"&gt;50K" or "&lt;=50K", meaning  whether the person makes more  than \$50,000 annually.</td>
</tr>
</tbody>
</table>

## Follow the Directions in Bold. If you get stuck, check out the solutions lecture.

### THE DATA

** Read in the census_data.csv data with pandas**

In [1]:
import pandas as pd

In [14]:
df = pd.read_csv('census_data.csv')

In [15]:
df.head()
#<=50K
#>50K

,age,workclass,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income_bracket
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

** TensorFlow won't be able to understand strings as labels, you'll need to use pandas .apply() method to apply a custom function that converts them to 0s and 1s. This might be hard if you aren't very familiar with pandas, so feel free to take a peek at the solutions for this part.**

** Convert the Label column to 0s and 1s instead of strings.**

In [16]:
df['native_country'].unique()

array([' United-States', ' Cuba', ' Jamaica', ' India', ' ?', ' Mexico',
       ' South', ' Puerto-Rico', ' Honduras', ' England', ' Canada',
       ' Germany', ' Iran', ' Philippines', ' Italy', ' Poland',
       ' Columbia', ' Cambodia', ' Thailand', ' Ecuador', ' Laos',
       ' Taiwan', ' Haiti', ' Portugal', ' Dominican-Republic',
       ' El-Salvador', ' France', ' Guatemala', ' China', ' Japan',
       ' Yugoslavia', ' Peru', ' Outlying-US(Guam-USVI-etc)', ' Scotland',
       ' Trinadad&Tobago', ' Greece', ' Nicaragua', ' Vietnam', ' Hong',
       ' Ireland', ' Hungary', ' Holand-Netherlands'], dtype=object)

In [17]:
def convertIncome(x):
    x = str(x).strip()
    if x == '<=50K':    
        return 0
    else:
        return 1

In [18]:
df['income_bracket'] = df['income_bracket'].apply(convertIncome)

,age,workclass,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income_bracket
32556,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
32557,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32558,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
32559,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0
32560,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,1

### Perform a Train Test Split on the Data

In [19]:
from sklearn.cross_validation import train_test_split

/usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [20]:
x_data = df.drop('income_bracket',axis=1)
y_labels = df['income_bracket']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_labels, test_size=0.3, random_state=101)

### Create the Feature Columns for tf.esitmator

** Take note of categorical vs continuous values! **

In [22]:
df.columns

Index(['age', 'workclass', 'education', 'education_num', 'marital_status',
       'occupation', 'relationship', 'race', 'gender', 'capital_gain',
       'capital_loss', 'hours_per_week', 'native_country', 'income_bracket'],
      dtype='object')

** Import Tensorflow **

In [23]:
import tensorflow as tf

** Create the tf.feature_columns for the categorical values. Use vocabulary lists or just use hash buckets. **

In [24]:
gender = tf.feature_column.categorical_column_with_vocabulary_list("gender",['Female','Male'])

In [25]:
occupation = tf.feature_column.categorical_column_with_hash_bucket("occupation",hash_bucket_size=1000)

In [26]:
marital_status = tf.feature_column.categorical_column_with_hash_bucket("marital_status", hash_bucket_size=1000)
relationship = tf.feature_column.categorical_column_with_hash_bucket("relationship", hash_bucket_size=1000)
education = tf.feature_column.categorical_column_with_hash_bucket("education", hash_bucket_size=1000)
workclass = tf.feature_column.categorical_column_with_hash_bucket("workclass", hash_bucket_size=1000)
native_country = tf.feature_column.categorical_column_with_hash_bucket("native_country", hash_bucket_size=1000)

** Create the continuous feature_columns for the continuous values using numeric_column **

In [28]:
age = tf.feature_column.numeric_column("age")
education_num = tf.feature_column.numeric_column("education_num")
capital_gain = tf.feature_column.numeric_column("capital_gain")
capital_loss = tf.feature_column.numeric_column("capital_loss")
hours_per_week = tf.feature_column.numeric_column("hours_per_week")

** Put all these variables into a single list with the variable name feat_cols **

In [29]:
feat_cols = [gender,occupation,marital_status,relationship,education,workclass,native_country,
            age,education_num,capital_gain,capital_loss,hours_per_week]

### Create Input Function

** Batch_size is up to you. But do make sure to shuffle!**

In [30]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,batch_size=100,num_epochs=None,shuffle=True)

#### Create your model with tf.estimator

**Create a LinearClassifier.(If you want to use a DNNClassifier, keep in mind you'll need to create embedded columns out of the cateogrical feature that use strings, check out the previous lecture on this for more info.)**

In [31]:
model = tf.estimator.LinearClassifier(feature_columns=feat_cols)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpu9vxxifi
INFO:tensorflow:Using config: {'_save_summary_steps': 100, '_keep_checkpoint_every_n_hours': 10000, '_save_checkpoints_steps': None, '_session_config': None, '_master': '', '_task_id': 0, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_model_dir': '/tmp/tmpu9vxxifi', '_keep_checkpoint_max': 5, '_task_type': 'worker', '_service': None, '_is_chief': True, '_tf_random_seed': None, '_log_step_count_steps': 100, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f8c4d6462b0>, '_save_checkpoints_secs': 600}

** Train your model on the data, for at least 5000 steps. **

In [32]:
model.train(input_fn=input_func,steps=10000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/tmpu9vxxifi/model.ckpt.
INFO:tensorflow:loss = 69.3147, step = 1
INFO:tensorflow:global_step/sec: 131.377
INFO:tensorflow:loss = 141.344, step = 101 (0.762 sec)
INFO:tensorflow:global_step/sec: 193.448
INFO:tensorflow:loss = 68.0928, step = 201 (0.517 sec)
INFO:tensorflow:global_step/sec: 196.247
INFO:tensorflow:loss = 538.027, step = 301 (0.510 sec)
INFO:tensorflow:global_step/sec: 194.545
INFO:tensorflow:loss = 43.6455, step = 401 (0.514 sec)
INFO:tensorflow:global_step/sec: 239.269
INFO:tensorflow:loss = 133.861, step = 501 (0.420 sec)
INFO:tensorflow:global_step/sec: 195.195
INFO:tensorflow:loss = 293.659, step = 601 (0.511 sec)
INFO:tensorflow:global_step/sec: 189.366
INFO:tensorflow:loss = 62.9716, step = 701 (0.528 sec)
INFO:tensorflow:global_step/sec: 195.112
INFO:tensorflow:loss = 116.57, step = 801 (0.512 sec)
INFO:tensorflow:global_step/sec: 244.3
INFO:tensorflow:loss = 46.3658, step = 901 (0.410 sec)
INFO:tensorflow:global_step/sec: 196.605
INFO:tensorflow:loss = 70.4882, step = 1001 (0.509 sec)
INFO:tensorflow:global_step/sec: 182.605
INFO:tensorflow:loss = 49.5596, step = 1101 (0.547 sec)
INFO:tensorflow:global_step/sec: 196.38
INFO:tensorflow:loss = 109.25, step = 1201 (0.511 sec)
INFO:tensorflow:global_step/sec: 189.379
INFO:tensorflow:loss = 52.9345, step = 1301 (0.526 sec)
INFO:tensorflow:global_step/sec: 202.793
INFO:tensorflow:loss = 160.812, step = 1401 (0.494 sec)
INFO:tensorflow:global_step/sec: 203.147
INFO:tensorflow:loss = 135.655, step = 1501 (0.491 sec)
INFO:tensorflow:global_step/sec: 199.528
INFO:tensorflow:loss = 203.559, step = 1601 (0.503 sec)
INFO:tensorflow:global_step/sec: 198.918
INFO:tensorflow:loss = 188.401, step = 1701 (0.501 sec)
INFO:tensorflow:global_step/sec: 189.949
INFO:tensorflow:loss = 112.319, step = 1801 (0.527 sec)
INFO:tensorflow:global_step/sec: 202.026
INFO:tensorflow:loss = 80.7181, step = 1901 (0.497 sec)
INFO:tensorflow:global_step/sec: 184.589
INFO:tensorflow:loss = 60.1572, step = 2001 (0.539 sec)
INFO:tensorflow:global_step/sec: 206.783
INFO:tensorflow:loss = 55.3431, step = 2101 (0.483 sec)
INFO:tensorflow:global_step/sec: 194.906
INFO:tensorflow:loss = 100.321, step = 2201 (0.513 sec)
INFO:tensorflow:global_step/sec: 171.914
INFO:tensorflow:loss = 38.5854, step = 2301 (0.582 sec)
INFO:tensorflow:global_step/sec: 230.455
INFO:tensorflow:loss = 44.0963, step = 2401 (0.436 sec)
INFO:tensorflow:global_step/sec: 190.465
INFO:tensorflow:loss = 35.6424, step = 2501 (0.524 sec)
INFO:tensorflow:global_step/sec: 197.475
INFO:tensorflow:loss = 42.0055, step = 2601 (0.506 sec)
INFO:tensorflow:global_step/sec: 200.063
INFO:tensorflow:loss = 140.875, step = 2701 (0.499 sec)
INFO:tensorflow:global_step/sec: 246.203
INFO:tensorflow:loss = 35.2413, step = 2801 (0.407 sec)
INFO:tensorflow:global_step/sec: 214.26
INFO:tensorflow:loss = 27.4016, step = 2901 (0.467 sec)
INFO:tensorflow:global_step/sec: 220.085
INFO:tensorflow:loss = 90.4862, step = 3001 (0.455 sec)
INFO:tensorflow:global_step/sec: 195.761
INFO:tensorflow:loss = 145.927, step = 3101 (0.510 sec)
INFO:tensorflow:global_step/sec: 202.124
INFO:tensorflow:loss = 207.302, step = 3201 (0.495 sec)
INFO:tensorflow:global_step/sec: 202.339
INFO:tensorflow:loss = 34.2784, step = 3301 (0.494 sec)
INFO:tensorflow:global_step/sec: 191.301
INFO:tensorflow:loss = 62.3101, step = 3401 (0.522 sec)
INFO:tensorflow:global_step/sec: 194.742
INFO:tensorflow:loss = 35.9583, step = 3501 (0.513 sec)
INFO:tensorflow:global_step/sec: 213.905
INFO:tensorflow:loss = 37.8526, step = 3601 (0.469 sec)
INFO:tensorflow:global_step/sec: 254.034
INFO:tensorflow:loss = 47.7789, step = 3701 (0.392 sec)
INFO:tensorflow:global_step/sec: 193.413
INFO:tensorflow:loss = 27.8056, step = 3801 (0.519 sec)
INFO:tensorflow:global_step/sec: 193.072
INFO:tensorflow:loss = 38.7855, step = 3901 (0.516 sec)
INFO:tensorflow:global_step/sec: 192.064
INFO:tensorflow:loss = 28.9683, step = 4001 (0.520 sec)
INFO:tensorflow:global_step/sec: 196.525
INFO:tensorflow:loss = 37.8596, step = 4101 (0.508 sec)
INFO:tensorflow:global_step/sec: 190.121
INFO:tensorflow:loss = 104.702, step = 4201 (0.527 sec)
INFO:tensorflow:global_step/sec: 202.896
INFO:tensorflow:loss = 104.223, step = 4301 (0.493 sec)
INFO:tensorflow:global_step/sec: 193.798
INFO:tensorflow:loss = 26.2473, step = 4401 (0.516 sec)
INFO:tensorflow:global_step/sec: 195.474
INFO:tensorflow:loss = 76.5839, step = 4501 (0.513 sec)
INFO:tensorflow:global_step/sec: 193.36
INFO:tensorflow:loss = 45.6284, step = 4601 (0.516 sec)
INFO:tensorflow:global_step/sec: 211.295
INFO:tensorflow:loss = 36.0897, step = 4701 (0.473 sec)
INFO:tensorflow:global_step/sec: 186.326
INFO:tensorflow:loss = 80.5822, step = 4801 (0.537 sec)
INFO:tensorflow:global_step/sec: 196.793
INFO:tensorflow:loss = 33.0371, step = 4901 (0.510 sec)
INFO:tensorflow:global_step/sec: 175.263
INFO:tensorflow:loss = 118.82, step = 5001 (0.569 sec)
INFO:tensorflow:global_step/sec: 188.329
INFO:tensorflow:loss = 24.2084, step = 5101 (0.530 sec)
INFO:tensorflow:global_step/sec: 189.18
INFO:tensorflow:loss = 177.094, step = 5201 (0.529 sec)
INFO:tensorflow:global_step/sec: 199.762
INFO:tensorflow:loss = 36.8088, step = 5301 (0.501 sec)
INFO:tensorflow:global_step/sec: 203.318
INFO:tensorflow:loss = 37.8647, step = 5401 (0.492 sec)
INFO:tensorflow:global_step/sec: 189.251
INFO:tensorflow:loss = 35.2712, step = 5501 (0.530 sec)
INFO:tensorflow:global_step/sec: 199.408
INFO:tensorflow:loss = 30.4404, step = 5601 (0.500 sec)
INFO:tensorflow:global_step/sec: 197.177
INFO:tensorflow:loss = 59.9224, step = 5701 (0.508 sec)
INFO:tensorflow:global_step/sec: 212.416
INFO:tensorflow:loss = 29.5608, step = 5801 (0.470 sec)
INFO:tensorflow:global_step/sec: 209.899
INFO:tensorflow:loss = 35.1152, step = 5901 (0.477 sec)
INFO:tensorflow:global_step/sec: 191.954
INFO:tensorflow:loss = 49.8097, step = 6001 (0.521 sec)
INFO:tensorflow:global_step/sec: 195.738
INFO:tensorflow:loss = 32.1704, step = 6101 (0.510 sec)
INFO:tensorflow:global_step/sec: 220.321
INFO:tensorflow:loss = 82.0948, step = 6201 (0.454 sec)
INFO:tensorflow:global_step/sec: 204.282
INFO:tensorflow:loss = 43.6124, step = 6301 (0.491 sec)
INFO:tensorflow:global_step/sec: 193.541
INFO:tensorflow:loss = 1324.66, step = 6401 (0.515 sec)
INFO:tensorflow:global_step/sec: 263.639
INFO:tensorflow:loss = 38.4466, step = 6501 (0.380 sec)
INFO:tensorflow:global_step/sec: 207.125
INFO:tensorflow:loss = 41.9846, step = 6601 (0.483 sec)
INFO:tensorflow:global_step/sec: 240.936
INFO:tensorflow:loss = 124.456, step = 6701 (0.417 sec)
INFO:tensorflow:global_step/sec: 201.732
INFO:tensorflow:loss = 33.6801, step = 6801 (0.494 sec)
INFO:tensorflow:global_step/sec: 265.599
INFO:tensorflow:loss = 45.9459, step = 6901 (0.378 sec)
INFO:tensorflow:global_step/sec: 194.037
INFO:tensorflow:loss = 58.7219, step = 7001 (0.514 sec)
INFO:tensorflow:global_step/sec: 214.814
INFO:tensorflow:loss = 25.6364, step = 7101 (0.466 sec)
INFO:tensorflow:global_step/sec: 204.886
INFO:tensorflow:loss = 50.5221, step = 7201 (0.488 sec)
INFO:tensorflow:global_step/sec: 194.674
INFO:tensorflow:loss = 25.8009, step = 7301 (0.514 sec)
INFO:tensorflow:global_step/sec: 189.277
INFO:tensorflow:loss = 24.3147, step = 7401 (0.530 sec)
INFO:tensorflow:global_step/sec: 198.13
INFO:tensorflow:loss = 29.7396, step = 7501 (0.507 sec)
INFO:tensorflow:global_step/sec: 191.636
INFO:tensorflow:loss = 36.3795, step = 7601 (0.519 sec)
INFO:tensorflow:global_step/sec: 193.697
INFO:tensorflow:loss = 43.8545, step = 7701 (0.516 sec)
INFO:tensorflow:global_step/sec: 209.579
INFO:tensorflow:loss = 35.1762, step = 7801 (0.480 sec)
INFO:tensorflow:global_step/sec: 193.605
INFO:tensorflow:loss = 29.0795, step = 7901 (0.514 sec)
INFO:tensorflow:global_step/sec: 194.787
INFO:tensorflow:loss = 493.075, step = 8001 (0.513 sec)
INFO:tensorflow:global_step/sec: 219.877
INFO:tensorflow:loss = 24.0778, step = 8101 (0.455 sec)
INFO:tensorflow:global_step/sec: 194.996
INFO:tensorflow:loss = 202.577, step = 8201 (0.513 sec)
INFO:tensorflow:global_step/sec: 187.698
INFO:tensorflow:loss = 56.5628, step = 8301 (0.532 sec)
INFO:tensorflow:global_step/sec: 207.847
INFO:tensorflow:loss = 249.972, step = 8401 (0.481 sec)
INFO:tensorflow:global_step/sec: 200.925
INFO:tensorflow:loss = 26.851, step = 8501 (0.499 sec)
INFO:tensorflow:global_step/sec: 190.446
INFO:tensorflow:loss = 36.7704, step = 8601 (0.526 sec)
INFO:tensorflow:global_step/sec: 200.796
INFO:tensorflow:loss = 33.9825, step = 8701 (0.496 sec)
INFO:tensorflow:global_step/sec: 191.641
INFO:tensorflow:loss = 35.6349, step = 8801 (0.523 sec)
INFO:tensorflow:global_step/sec: 195.074
INFO:tensorflow:loss = 167.452, step = 8901 (0.513 sec)
INFO:tensorflow:global_step/sec: 190.894
INFO:tensorflow:loss = 144.023, step = 9001 (0.522 sec)
INFO:tensorflow:global_step/sec: 212.002
INFO:tensorflow:loss = 26.1528, step = 9101 (0.472 sec)
INFO:tensorflow:global_step/sec: 214.348
INFO:tensorflow:loss = 40.3989, step = 9201 (0.467 sec)
INFO:tensorflow:global_step/sec: 223.568
INFO:tensorflow:loss = 51.6615, step = 9301 (0.447 sec)
INFO:tensorflow:global_step/sec: 214.231
INFO:tensorflow:loss = 45.753, step = 9401 (0.468 sec)
INFO:tensorflow:global_step/sec: 194.967
INFO:tensorflow:loss = 31.107, step = 9501 (0.511 sec)
INFO:tensorflow:global_step/sec: 199.201
INFO:tensorflow:loss = 113.074, step = 9601 (0.502 sec)
INFO:tensorflow:global_step/sec: 197.946
INFO:tensorflow:loss = 27.8861, step = 9701 (0.505 sec)
INFO:tensorflow:global_step/sec: 197.975
INFO:tensorflow:loss = 27.1225, step = 9801 (0.505 sec)
INFO:tensorflow:global_step/sec: 221.723
INFO:tensorflow:loss = 108.956, step = 9901 (0.450 sec)
INFO:tensorflow:Saving checkpoints for 10000 into /tmp/tmpu9vxxifi/model.ckpt.
INFO:tensorflow:Loss for final step: 21.0131.

### Evaluation

** Create a prediction input function. Remember to only supprt X_test data and keep shuffle=False. **

In [33]:
pred_fn = tf.estimator.inputs.pandas_input_fn(x=X_test,batch_size=len(X_test),shuffle=False)

** Use model.predict() and pass in your input function. This will produce a generator of predictions, which you can then transform into a list, with list() **

In [34]:
pred_gen = model.predict(input_fn=pred_fn)

** Each item in your list will look like this: **

In [36]:
predictions = list(pred_gen)

INFO:tensorflow:Restoring parameters from /tmp/tmpu9vxxifi/model.ckpt-10000

** Create a list of only the class_ids key values from the prediction list of dictionaries, these are the predictions you will use to compare against the real y_test values. **

In [37]:
final_preds = [pred['class_ids'][0] for pred in predictions]

In [38]:
final_preds

[0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 ...]

** Import classification_report from sklearn.metrics and then see if you can figure out how to use it to easily get a full report of your model's performance on the test data. **

In [39]:
from sklearn.metrics import classification_report

In [41]:
print(classification_report(y_test,final_preds))

             precision    recall  f1-score   support

          0       0.89      0.92      0.91      7436
          1       0.72      0.64      0.68      2333

avg / total       0.85      0.85      0.85      9769

# Great Job!